#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""spec.py —— 9 把自定义武器的**清单**：谁参考谁、新编号是什么、资源改什么名（X_Mod · X3）。

`preview.py`（效果图）和 `build.py`（实装）都从这里取数，别在两边各抄一份。

编号口径（计划 §二）：
    物品 id   X 92 000 S      X = 角色 1/2/3，S = 槽位 1/2/3            → 1920001 …
    武器 Id   1 0 0C 3 S 5    C = 角色 0/1/2，S = 槽位，档 3 = 「D 系第 4 档」→ 1000315 …
    碎片 Id   1 0 0C 5 3 5    只有泰尔 / 卡希尔的 2 号有子弹药            → 1000535 / 1001535

★★ 武器 Id 不是随便编的，客户端会**拆数位**（§41 / D31）：
    系列 = Id % 10；索引 = (Id / 10) % 100；若 3 ≤ 系列 ≤ 5 且 索引 < 50 则 索引 %= 10。
    这个索引直接拿去下标**只有 4 格**的弹药数组，而且三个调用点都**只查 >= 0、不查上界**。
    ⇒ 新编号必须满足「系列 ∈ [3,5] 且 档*10+槽 < 50」，否则索引越界：
      既永远不换弹（把堆里的指针当弹药数），又每开一枪往堆里乱写一个 dword。
    初版用的 `1 0 0C 9 S 0`（档 9、系列 0）正好两条都踩，实机表现是
    「自定义武器无限开火 + 结算界面卡死」。**别再把档改回 ≥ 5 或把系列改出 [3,5]。**
    手持网格  chNN W 014S     爆裂 3 是 013S，等长改名（贴图同名）
    3D 弹体   chNN D 0142     只有泰尔 / 卡希尔 2 号（爆裂 3 是 D0132）
    amf 条目  CHnn_WPk_C      爆裂 3 是 CHnn_WPk_D3（有 D3W 的再加一条 CW，指同一张图）
    HUD 图集  Wp0kC           爆裂 3 是 Wp0kD3，3 帧 = 3 个角色
    商店图标  무기_<韩文名> C   爆裂 3 是 무기_<韩文名> D3
    ini 小节  [chNN-0SC]      Name = <韩文名> C
"""
from __future__ import annotations

import collections
import os
import re
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
TOOLS = os.path.dirname(HERE)
ROOT = os.path.dirname(TOOLS)

#: 自定义系列的字母（小节名后缀 / 韩文名后缀 / 资源名里代替 `D3` 的那一段）。
SERIES = "C"

#: 原版 `weapon.ini`（CP949 + CRLF，221519 B）的哈希。`2245b8c7^` 那份 == `main/Pack_decrypt` 那份。
#: ★ 放在这个**只依赖标准库**的模块里：`test/test_weaponini.py` 要拿它核对，而 `build.py`
#: 顶层 import numpy / Pillow（便携运行时里没有）。
ORIGINAL_SHA256 = "00084834adea094c8bb038ad08627886e32b2224fd08238d0d26eb0d8db81616"
ORIGINAL_SIZE = 221519

#: 追加块的第一行。客户端的 ini 读取器把 `;` 开头当注释（原版 ini 里就有 `;` 行）。
INI_MARKER = "; ==== X_Mod goldwp: custom weapons (generated by tools/goldwp/build.py, do not edit by hand) ===="

Weapon = collections.namedtuple(
    "Weapon",
    "character slot item_id ammo_id piece_id section piece_section "
    "custom_section custom_piece_section mesh_idx icon_set shop_icon_kr")

#: 三个角色 × 3 槽。`section` 是参考的爆裂 3 小节（大小写照原文件），
#: `shop_icon_kr` 是商店图标文件名里那段韩文（`무기_<它> D3.png`）。
WEAPONS = (
    Weapon(0, 1, 1920001, 1000315, None,    "ch00-01D3", None,        "ch00-01C", None,       141, "Wp01", "리볼버"),
    Weapon(0, 2, 1920002, 1000325, 1000535, "ch00-02D3", "ch00-02D3a", "ch00-02C", "ch00-02Ca", 142, "Wp02", "사과탄"),
    Weapon(0, 3, 1920003, 1000335, None,    "ch00-03D3", None,        "ch00-03C", None,       143, "Wp03", "T1"),
    Weapon(1, 1, 2920001, 1001315, None,    "CH01-01D3", None,        "ch01-01C", None,       141, "Wp01", "카멜나이트"),
    Weapon(1, 2, 2920002, 1001325, 1001535, "ch01-02D3", "ch01-02D3a", "ch01-02C", "ch01-02Ca", 142, "Wp02", "화염탄"),
    Weapon(1, 3, 2920003, 1001335, None,    "ch01-03D3", None,        "ch01-03C", None,       143, "Wp03", "캐논왈츠"),
    Weapon(2, 1, 3920001, 1002315, None,    "ch02-01D3", None,        "ch02-01C", None,       141, "Wp01", "머신건"),
    Weapon(2, 2, 3920002, 1002325, None,    "ch02-02D3", None,        "ch02-02C", None,       142, "Wp02", "스크류런처"),
    Weapon(2, 3, 3920003, 1002335, None,    "ch02-03D3", None,        "ch02-03C", None,       143, "Wp03", "바주카"),
)

#: 客户端 `0x40a138` 的武器 Id 解码器，原样照抄（§41）。返回 `(系列, 索引)`。
#: `weapon_slot_index()` 必须等于槽位，否则弹药数组越界 —— `test_weaponini` 拿它守着。
def decode_weapon_id(weapon_id):
    """照 `0x40a138` 原样实现：系列 = Id%10，索引 = (Id/10)%100，D/R/F 系再归一化成槽位。"""
    series = weapon_id % 10
    index = (weapon_id // 10) % 100
    if 3 <= series <= 5 and index < 50:
        index %= 10
    return series, index


def weapon_slot_index(weapon_id):
    """客户端拿来下标弹药数组的那个索引。"""
    return decode_weapon_id(weapon_id)[1]

WEAPON_SLOT_FLAG = {1: 1024, 2: 2048, 3: 4096}


def develop_root():
    server_dir = os.path.join(ROOT, "server")
    if server_dir not in sys.path:
        sys.path.append(server_dir)
    import config
    return os.path.join(ROOT, "game_patched", config.PACK_DEVELOP_DIR)


def chars_dir(character):
    return os.path.join(develop_root(), "Models", "Characters", "ch%02d" % character)


def read_weapon_ini(path=None):
    """`weapon.ini` → `OrderedDict{节名: OrderedDict{键: 值}}`，**保留 `#` 注释键**
    （`#CoolingTime=2000` 这种原版注释掉的行原样带走，客户端本来就当它不存在）。
    编码走 `tools/weapondata.read_ini` 同一套嗅探。"""
    import importlib.util
    spec = importlib.util.spec_from_file_location("goldwp_weapondata",
                                                  os.path.join(TOOLS, "weapondata.py"))
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    path = path or os.path.join(develop_root(), "Data", "weapon.ini")
    with open(path, "rb") as fp:
        raw = fp.read()
    if raw[:2] == b"\xff\xfe":
        text = raw.decode("utf-16le", "replace")
    else:
        try:
            text = raw.decode("cp949")
        except UnicodeDecodeError:
            text = raw.decode("cp936", "replace")
    sections = collections.OrderedDict()
    current = None
    for line in text.splitlines():
        line = line.strip().lstrip("﻿")
        if not line or line.startswith(";"):
            continue
        if line.startswith("[") and line.endswith("]"):
            current = line[1:-1].strip()
            sections[current] = collections.OrderedDict()
            continue
        if current is None or "=" not in line:
            continue
        key, value = line.split("=", 1)
        sections[current][key.strip()] = value.strip()
    return sections


def d3_sections(sections):
    """`{自定义小节名: 参考小节的字段表}`，9 主 + 2 子。"""
    out = collections.OrderedDict()
    for w in WEAPONS:
        out[w.custom_section] = sections[w.section]
        if w.piece_section:
            out[w.custom_piece_section] = sections[w.piece_section]
    return out


_D3 = re.compile(r"D3", re.IGNORECASE)


def rename(stem):
    """资源文件名里的 `D3` → `C`；没有 `D3` 的（原版笔误 / 共用件）在末尾加 `_C`。"""
    if _D3.search(stem):
        return _D3.sub(SERIES, stem, count=1)
    return stem + "_" + SERIES


def weapon_by_section(name):
    for w in WEAPONS:
        if w.section.lower() == name.lower() or (w.piece_section and w.piece_section.lower() == name.lower()):
            return w
    raise KeyError(name)
