#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""spec.py —— 自定义武器的**清单**：谁参考谁、新编号是什么、资源改什么名（X_Mod · X3 / X6）。

`preview.py`（效果图）和 `build.py`（实装）都从这里取数，别在两边各抄一份。

## 两批（`BATCHES`）

| 批次 | 母本 | 配色 | 部位码 | 武器 Id | 中文名 |
|---|---|---|---|---|---|
| `C` | 爆裂 3（`D3`）| 黄金 + 银白 | 92 | `1 0 0C 3 S 5` | 「xxx 自定义1」|
| `P` | 复合 3（`F3`）| 粉 + 绿 | 93 | `1 0 0C 4 S 5` | 「xxx 自定义2」|

★ `WEAPONS` 是**两批拼起来的 18 条**，不是某一批 —— `build.py` / `test_weaponini.py`
里所有 `for w in WEAPONS` 因此自动覆盖全部批次，加第三批也不用改那些循环。
★ `WEAPONS[0].item_id` 必须一直是 `1920001`：`tools/openweapons.py` 的 `GOLDWP_ANCHOR`
钉着它（那 18 件原版 3 级武器插在本块**之前**），`test_openweapons` 守着这条位置关系。

编号口径：

    物品 id   X <部位码> 000 S    X = 角色 1/2/3，S = 槽位 1/2/3   → 1920001… / 1930001…
    武器 Id   1 0 0C T S E        C = 角色 0/1/2，S = 槽位          → 1000315… / 1000415…
                                  T = 档位（原版 0/1/2），E = 系列位（D=5 / R=3 / F=4）
    子弹药 Id 1 0 0C 5 T E        只有泰尔 / 卡希尔的 2 号有        → 1000535 / 1000545

★★ 武器 Id 不是随便编的，客户端会**拆数位**（§41 / D31）：
    系列 = Id % 10；索引 = (Id / 10) % 100；若 3 ≤ 系列 ≤ 5 且 索引 < 50 则 索引 %= 10。
    这个索引直接拿去下标**只有 4 格**的弹药数组，而且三个调用点都**只查 >= 0、不查上界**。
    ⇒ 新编号必须满足「系列 ∈ [3,5] 且 档*10+槽 < 50」，否则索引越界：
      既永远不换弹（把堆里的指针当弹药数），又每开一枪往堆里乱写一个 dword。
    初版用的 `1 0 0C 9 S 0`（档 9、系列 0）正好两条都踩，实机表现是
    「自定义武器无限开火 + 结算界面卡死」。**别再把档改回 ≥ 5 或把系列改出 [3,5]。**
    ⚠ 合法组合只有 `档 ∈ {0..4} × 系列 ∈ {3,4,5}` 共 15 个：原版占 9 个、C 占 (3,5)、
      P 占 (4,5)，**只剩 4 个**。第三批必须改系列位（档已经用到头了）。

    手持网格  chNN W 0<系><档><槽>    C 是 014S（爆裂 3 的 013S）、P 是 034S（复合 3 的 033S）
    3D 弹体   chNN D 0<系><档>2      同上，只有泰尔 / 卡希尔的 2 号
    amf 条目  CHnn_WPk_<字母>        母本是 CHnn_WPk_D3 / _F3（有 …W 的再加一条，指同一张图）
    HUD 图集  Wp0k<字母>             母本是 Wp0kD3 / Wp0kF3，3 帧 = 3 个角色
    商店图标  무기_<韩文名> <字母>     母本是 무기_<韩文名> D3 / F3
    ini 小节  [chNN-0S<字母>]        Name = <韩文名> <字母>
"""
from __future__ import annotations

import collections
import os
import re
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
TOOLS = os.path.dirname(HERE)
ROOT = os.path.dirname(TOOLS)

#: 原版 `weapon.ini`（CP949 + CRLF，221519 B）的哈希。`2245b8c7^` 那份 == `main/Pack_decrypt` 那份。
#: ★ 放在这个**只依赖标准库**的模块里：`test/test_weaponini.py` 要拿它核对，而 `build.py`
#: 顶层 import numpy / Pillow（便携运行时里没有）。
ORIGINAL_SHA256 = "00084834adea094c8bb038ad08627886e32b2224fd08238d0d26eb0d8db81616"
ORIGINAL_SIZE = 221519

#: 追加块的第一行。客户端的 ini 读取器把 `;` 开头当注释（原版 ini 里就有 `;` 行）。
#: ★ **只有这一个标记**：两批的小节写在同一块里（`build.py` 砍掉标记之后的一切再整块重写）。
INI_MARKER = "; ==== X_Mod goldwp: custom weapons (generated by tools/goldwp/build.py, do not edit by hand) ===="

Batch = collections.namedtuple(
    "Batch", "letter src_stem scheme variant item_part id_tier id_series")
Weapon = collections.namedtuple(
    "Weapon",
    "character slot item_id ammo_id piece_id section piece_section "
    "custom_section custom_piece_section mesh_idx icon_set shop_icon_kr batch")

#: `WMeshIdx` 的百位（`tools/shopdata.SERIES_NAMES`：D 爆裂 / R 极速 / F 复合）。
#: ★ 母本一律取各系列的**第 3 档**（`x3S`），产物固定是**第 4 档**（`x4S`，磁盘上全空）
#:   ⇒ `目标 mesh_idx - 10 == 母本 mesh_idx` 对每一批都成立，`build.py` / `preview.py` 靠它找母本。
_MESH_SERIES = {"D3": 1, "R3": 2, "F3": 3}

#: 批次表。`scheme` 是 `palette.SCHEMES` 的键，`variant` 是那个方案里选定的撞色变体
#: （`None` = 还没定：`build.py` 拒绝跑，`preview.py` 照样能渲）。
#:
#: ★★ `id_tier` / `id_series` 是**武器 Id** 那两位，和母本的系列**故意解耦**：
#:   P 批的模型来自复合 3（网格走 F 系的 `34S`），但武器 Id 仍走 **D 系第 5 档**（`…4S5`）——
#:   和 C 批相比只有档位一位变，客户端所有「按系列分支」的代码走的是**已经实机跑过一轮的那条路**；
#:   而模型 / 图标 / 弹体 / 特效全由 ini 记录里的字段显式指定，和系列位无关（D31 同一个理由）。
BATCHES = collections.OrderedDict((b.letter, b) for b in (
    #     字母  母本   配色方案  变体  部位码  Id档 Id系列
    Batch("C", "D3", "gold", "C", 92, 3, 5),     # 爆裂 3 → 黄金 + 银白（用户 2026-09-19 选 C）
    Batch("P", "F3", "pink", "P7", 93, 4, 5),    # 复合 3 → 樱花粉 + 抹茶绿（用户 2026-09-19 选 P7）
))


def _rows(batch):
    """一批 9 把的清单。母本小节 / 韩文名 / 图集照 `_SOURCES` 取，编号和字母按批次算。"""
    out = []
    for character, slot, section, shop_icon_kr, piece in _SOURCES:
        letter, stem = batch.letter, batch.src_stem
        base = 1000000 + character * 1000 + batch.id_series
        out.append(Weapon(
            character=character,
            slot=slot,
            item_id=(character + 1) * 1000000 + batch.item_part * 10000 + slot,
            ammo_id=base + batch.id_tier * 100 + slot * 10,
            piece_id=(base + 500 + batch.id_tier * 10) if piece else None,
            section=section % stem,
            piece_section=(section % stem + "a") if piece else None,
            custom_section="ch%02d-0%d%s" % (character, slot, letter),
            custom_piece_section=("ch%02d-0%d%sa" % (character, slot, letter)) if piece else None,
            mesh_idx=_MESH_SERIES[stem] * 100 + 40 + slot,
            icon_set="Wp0%d" % slot,
            shop_icon_kr=shop_icon_kr,
            batch=letter))
    return tuple(out)

#: 9 个槽位的母本：`(角色, 槽, 小节名模板, 商店图标里那段韩文, 有没有子弹药)`。
#: ★ `CH01-01%s` 的大小写照原 ini 抄（`read_weapon_ini` 不折大小写）。
_SOURCES = (
    (0, 1, "ch00-01%s", "리볼버", False),
    (0, 2, "ch00-02%s", "사과탄", True),
    (0, 3, "ch00-03%s", "T1", False),
    (1, 1, "CH01-01%s", "카멜나이트", False),
    (1, 2, "ch01-02%s", "화염탄", True),
    (1, 3, "ch01-03%s", "캐논왈츠", False),
    (2, 1, "ch02-01%s", "머신건", False),
    (2, 2, "ch02-02%s", "스크류런처", False),
    (2, 3, "ch02-03%s", "바주카", False),
)

#: ★ 两批拼起来的 18 条。顺序 = `BATCHES` 的顺序，`WEAPONS[0]` 必须是 `1920001`（见文件头）。
WEAPONS = tuple(w for b in BATCHES.values() for w in _rows(b))


def batch_of(weapon):
    """一把武器属于哪个批次。"""
    return BATCHES[weapon.batch]


def weapons_of(letter):
    """某一批的 9 条。"""
    return tuple(w for w in WEAPONS if w.batch == letter)


#: 客户端 `0x40a138` 的武器 Id 解码器，原样照抄（§41）。返回 `(系列, 索引)`。
#: `weapon_slot_index()` 必须等于槽位，否则弹药数组越界 —— `test_weaponini` 拿它守着。
def decode_weapon_id(weapon_id):
    """照 `0x40a138` 原样实现：系列 = Id%10，索引 = (Id/10)%100，D/R/F 系再归一化成槽位。"""
    series = weapon_id % 10
    index = (weapon_id // 10) % 100
    if 3 <= series <= 5 and index < 50:
        index %= 10
    return series, index


def weapon_slot_index(weapon_id):
    """客户端拿来下标弹药数组的那个索引。"""
    return decode_weapon_id(weapon_id)[1]

WEAPON_SLOT_FLAG = {1: 1024, 2: 2048, 3: 4096}


def develop_root():
    server_dir = os.path.join(ROOT, "server")
    if server_dir not in sys.path:
        sys.path.append(server_dir)
    import config
    return os.path.join(ROOT, "game_patched", config.PACK_DEVELOP_DIR)


def chars_dir(character):
    return os.path.join(develop_root(), "Models", "Characters", "ch%02d" % character)


def read_weapon_ini(path=None):
    """`weapon.ini` → `OrderedDict{节名: OrderedDict{键: 值}}`，**保留 `#` 注释键**
    （`#CoolingTime=2000` 这种原版注释掉的行原样带走，客户端本来就当它不存在）。
    编码走 `tools/weapondata.read_ini` 同一套嗅探。"""
    import importlib.util
    spec = importlib.util.spec_from_file_location("goldwp_weapondata",
                                                  os.path.join(TOOLS, "weapondata.py"))
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    path = path or os.path.join(develop_root(), "Data", "weapon.ini")
    with open(path, "rb") as fp:
        raw = fp.read()
    if raw[:2] == b"\xff\xfe":
        text = raw.decode("utf-16le", "replace")
    else:
        try:
            text = raw.decode("cp949")
        except UnicodeDecodeError:
            text = raw.decode("cp936", "replace")
    sections = collections.OrderedDict()
    current = None
    for line in text.splitlines():
        line = line.strip().lstrip("﻿")
        if not line or line.startswith(";"):
            continue
        if line.startswith("[") and line.endswith("]"):
            current = line[1:-1].strip()
            sections[current] = collections.OrderedDict()
            continue
        if current is None or "=" not in line:
            continue
        key, value = line.split("=", 1)
        sections[current][key.strip()] = value.strip()
    return sections


def src_sections(sections, weapons=None):
    """`{自定义小节名: 参考小节的字段表}`，每批 9 主 + 子弹药，按 `WEAPONS` 顺序。"""
    out = collections.OrderedDict()
    for w in (weapons if weapons is not None else WEAPONS):
        out[w.custom_section] = sections[w.section]
        if w.piece_section:
            out[w.custom_piece_section] = sections[w.piece_section]
    return out


#: 兼容老名字（`preview.py` 一度这么叫）。
d3_sections = src_sections


def rename(stem, weapon_or_batch):
    """资源文件名里的母本系列（`D3` / `F3`）→ 批次字母；没有的（原版笔误 / 共用件）在末尾加 `_<字母>`。

    ★ 正则必须是整个 `D3` / `F3` 两个字符，**不能只写 `F`** —— 复合 3 的 efx 大量引用
      `CH00_Wp01F1_*.dds` / `*F2_*.dds` 这类跨档共用的贴图，只匹配 `F` 会把它们一起改名、撞名。
    """
    batch = weapon_or_batch if isinstance(weapon_or_batch, Batch) else batch_of(weapon_or_batch)
    pattern = re.compile(re.escape(batch.src_stem), re.IGNORECASE)
    if pattern.search(stem):
        return pattern.sub(batch.letter, stem, count=1)
    return stem + "_" + batch.letter


def weapon_by_section(name):
    """按母本小节名或子弹药小节名找武器。★ 两批的母本不同，所以不会歧义。"""
    for w in WEAPONS:
        if w.section.lower() == name.lower() or (w.piece_section and w.piece_section.lower() == name.lower()):
            return w
    raise KeyError(name)
